version: "3.9"

services:
    site:
        build: .
        image: conjurer/user-needs-mapping.org:latest
        command: bundle exec jekyll serve --trace --host 0.0.0.0 --watch --incremental
        environment:
            - JEKYLL_ENV=development
        volumes:
            - ./:/srv/jekyll
        ports:
            - 4000:4000
